name: Testing
on: [push]
env:
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY}}
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install eth-brownie
      - run: brownie pm install OpenZeppelin/openzeppelin-contracts@4.6.0
      - run: brownie compile
      - run: brownie test
